# Generated by Django 4.0.4 on 2022-05-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrations', '0002_alter_fileupload_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='title',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
    ]
